version: "3.5"
services: 
  notificationsdb:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: yourStrong(!)Password
    image: microsoft/mssql-server-linux
    ports:
      - "1433"
    networks:
      - notification-service-network
  notifications:
    build: ./
    labels:
      SERVICE_NAME: NotificationService
    environment:
      SQLSERVER_HOST: Server=notificationsdb;User=sa;Password=yourStrong(!)Password
    depends_on:
      - notificationsdb
    ports: 
      - "5000:5000"
    networks: 
      - notification-service-network
networks:
  notification-service-network:
    name: quizrt-network
    external: true